var ddemkiw = {
  "login": "ddemkiw",
  "id": 9589145,
  "avatar_url": "https://avatars.githubusercontent.com/u/9589145?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/ddemkiw",
  "html_url": "https://github.com/ddemkiw",
  "followers_url": "https://api.github.com/users/ddemkiw/followers",
  "following_url": "https://api.github.com/users/ddemkiw/following{/other_user}",
  "gists_url": "https://api.github.com/users/ddemkiw/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/ddemkiw/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/ddemkiw/subscriptions",
  "organizations_url": "https://api.github.com/users/ddemkiw/orgs",
  "repos_url": "https://api.github.com/users/ddemkiw/repos",
  "events_url": "https://api.github.com/users/ddemkiw/events{/privacy}",
  "received_events_url": "https://api.github.com/users/ddemkiw/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Danielle ",
  "company": "Makers Academy",
  "blog": "",
  "location": "United Kingdom",
  "email": "ddemkiw@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 28,
  "public_gists": 0,
  "followers": 16,
  "following": 16,
  "created_at": "2014-11-06T10:45:58Z",
  "updated_at": "2015-02-05T12:03:07Z",
  "private_gists": 0,
  "total_private_repos": 0,
  "owned_private_repos": 0,
  "disk_usage": 4904,
  "collaborators": 0,
  "plan": {
    "name": "free",
    "space": 307200,
    "collaborators": 0,
    "private_repos": 0
  }
}

exports.ddemkiw = ddemkiw;